### PR TITLE
Use enums for implementations

### PR DESCRIPTION
**Pull request by ELC**
## What type of PR is this? (check all applicable)

- [X] 💾 Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📝 Documentation
- [ ] ✅ Test
- [ ] 🐳 Other

## Checklist

- [X] Code follows style guide (ruff)
- [N/A] Tests added 
- [N/A] Documented the changes

## Rationale

By using enums instead of strings we achieve:

1. Single source of truth: now to add a new backend, one only needs to modify the `narwhals/dependencies.py` file
2. Simplify contribution: by having enums in a single location and using `assert_never`, once a new value is added to the Enum, MyPy will flag all the places where modifications are needed, this is much easier to navigate than finding failed tests
3. For multi-backend implementations (such as pandas), a file called `implementations.py` is added showing the subset of implementations supported for that specific platform
4. Reduce boilerplate: with Enums and a couple of mappings, there is no longer a need for many if/elif/else logic, thus making the code easier to extend. There are several cases not yet addressed in this PR but now the only function used from `dependencies` is the `get_backend` rather than the individual `get_pandas`, etc.
5. Less error prone: by using enums, MyPy becomes much more helpful by actually detecting missing cases in the logic when new backends are added.

## Open questions:

This PR assumes `typing_extensions` is installed, this should be a relatively common case as most projects use this library, however, to keep narwhals dependency free, we would need to add `assert_never` to the utils. 

```python
import enum
from typing_extensions import NoReturn

def assert_never(arg: NoReturn) -> NoReturn:
    raise AssertionError("Expected code to be unreachable")
```
[Source](https://typing.readthedocs.io/en/latest/source/unreachable.html#assert-never-and-exhaustiveness-checking)

The `assert_never` and the `Never` type are included in Python 3.11 so this functionality should be explicitly made available to keep the library compatible with 3.8+

An interesting read on this topic is the following article by [Adam Johnson](https://adamj.eu/tech/2022/10/14/python-type-hints-exhuastiveness-checking/)

---

Would like to hear your thoughts on these changes @MarcoGorelli / @EdAbati

### CODE REVIEW

**Review by MarcoGorelli — COMMENTED** [review]
thanks for your PR! on board with the idea

File: narwhals/_pandas_like/dataframe.py [hunk 1]
```diff
@@ -8,16 +8,17 @@
 from typing import Literal
 from typing import overload
 
+from typing_extensions import assert_never
```
[the remark this answers is not in the document]
Comment (ELC) [reply narwhals/_pandas_like/dataframe.py:11]: Done

File: narwhals/_arrow/namespace.py [hunk 2]
```diff
@@ -53,7 +53,9 @@ def _create_expr_from_callable(  # noqa: PLR0913
             output_names=output_names,
         )
 
-    def _create_expr_from_series(self, series: ArrowSeries) -> ArrowExpr:
+    def _create_expr_from_series(
+        self, series: ArrowSeries
+    ) -> ArrowExpr:  # pragma: no cover
```
[the remark this answers is not in the document]
Comment (ELC) [reply narwhals/_arrow/namespace.py:58]: This was unexpected, I rebased to the latest main and this function was not 100% covered. None of this PR's change should have affected `_arrow`

I will investigate

[the remark this answers is not in the document]
Comment (francocastano) [reply narwhals/_arrow/namespace.py:58]: Which test is supposed to cover this function? @MarcoGorelli

**Comment by ELC** [comment]
@MarcoGorelli - This should be now ready to merge, however, there is a file without 100% coverage (not related to this PR):

image

File: narwhals/_pandas_like/group_by.py [hunk 3]
```diff
@@ -160,15 +160,16 @@ def func(df: Any) -> Any:
...
-    if implementation == "pandas":
-        pd = get_pandas()
+    extra_args: dict[str, Any] = {}
+    if implementation is Implementation.PANDAS:  # pragma: no cover
+        backend = get_backend(implementation)
+        backend_version = parse_version(backend.__version__)
+        minimum_version = parse_version("2.2.0")
+
+        if backend_version >= minimum_version:
+            extra_args["include_groups"] = False
```
Comment (EdAbati) [inline narwhals/_pandas_like/group_by.py:170]: (nitpicking, sorry) suggesting variable names and usage that I'd find more immediate/readable

```suggestion
    apply_kwargs: dict[str, Any] = {}
    if implementation is Implementation.PANDAS:  # pragma: no cover
        backend = get_backend(implementation)

        if parse_version(backend.__version__) >= parse_version("2.2.0"):
            apply_kwargs["include_groups"] = False
```

File: narwhals/_pandas_like/utils.py [hunk 4]
```diff
@@ -325,57 +321,46 @@ def vertical_concat(dfs: list[Any], implementation: str) -> Any:
...
 
-def set_axis(obj: T, index: Any, implementation: str) -> T:
-    if implementation == "pandas" and parse_version(
-        get_pandas().__version__
-    ) >= parse_version("1.5.0"):
+def set_axis(obj: T, index: Any, implementation: PANDAS_IMPLEMENTATIONS) -> T:
+    backend = get_backend(implementation)
+    backend_verison = parse_version(backend.__version__)
+    minimum_version = parse_version("1.5.0")
+    if implementation is Implementation.PANDAS and backend_verison >= minimum_version:
```
Comment (EdAbati) [inline narwhals/_pandas_like/utils.py:360]: (similar nitpicking)

```suggestion
    if implementation is Implementation.PANDAS and (
        backend_verison >= parse_version("1.5.0")
    ):
```

**Review by EdAbati — COMMENTED** [review]
Thanks for the PR! I really like the use of Enum here.

To solve the coverage issue , can you try to update `ArrowSeries` and `ArrowDataFrame` to use the `Implementation` enum? They still use the string

I also left 2 very minor comments

**Comment by ELC** [comment]
All the tests are passing now, however seems like there is some coverage issues in my local setup using ubuntu latest on a Github Codespace.

This is the main branch:
image

image

This is related to the recently merged cross join PR (#347)

Could we merge this anyway or should we wait until the coverage is 100% in main?

**Comment by MarcoGorelli** [comment]
> Could we merge this anyway or should we wait until the coverage is 100% in main?

sorry about that - it's 100% in CI, but some tests don't run locally. I've addressed that in https://github.com/narwhals-dev/narwhals/pull/379

File: .pre-commit-config.yaml [hunk 5]
```diff
@@ -12,7 +12,10 @@ repos:
   rev: 'v1.10.0'
   hooks:
     - id: mypy
-      additional_dependencies: ['polars==0.20.10', 'pytest==8.0.1']
+      additional_dependencies:
+        - "polars==0.20.10"
+        - "pytest==8.0.1"
+        - "typing-extensions==4.12.2"
```
Comment (MarcoGorelli) [inline .pre-commit-config.yaml:18]: isn't this already a dependency of mypy?

https://github.com/python/mypy/blob/d1d3c780c7a2d30b2a038903289ea7487303a218/pyproject.toml#L1-L15

File: narwhals/_pandas_like/dataframe.py [hunk 6]
```diff
@@ -290,10 +284,15 @@ def join(
...
 
         if how == "cross":
-            if self._implementation in {"modin", "cudf"} or (
-                self._implementation == "pandas"
-                and (pd := get_pandas()) is not None
-                and parse_version(pd.__version__) < parse_version("1.4.0")
+            backend = get_backend(self._implementation)
+            if (
+                self._implementation is Implementation.MODIN
+                or self._implementation is Implementation.CUDF
```
Comment (MarcoGorelli) [inline narwhals/_pandas_like/dataframe.py:290]: does `self._implementation in {Implementation.MODIN, Implementation.CUDF}` work?

File: narwhals/_pandas_like/implementations.py [hunk 7]
```diff
@@ -0,0 +1,22 @@
...
+from narwhals.dependencies import Implementation
+from narwhals.dependencies import get_backend
+from narwhals.typing import assert_never
+
+PANDAS_IMPLEMENTATIONS = Literal[
+    Implementation.PANDAS, Implementation.MODIN, Implementation.CUDF
+]
+
+
+def get_series_implementation(implementation: PANDAS_IMPLEMENTATIONS) -> Any:
```
Comment (MarcoGorelli) [inline narwhals/_pandas_like/implementations.py:14]: not sure about this function name tbh

File: narwhals/_pandas_like/utils.py [hunk 8]
```diff
@@ -325,57 +321,47 @@ def vertical_concat(dfs: list[Any], implementation: str) -> Any:
...
+    return series_implementation(data, name=name, index=index)
 
 
-def set_axis(obj: T, index: Any, implementation: str) -> T:
-    if implementation == "pandas" and parse_version(
-        get_pandas().__version__
-    ) >= parse_version("1.5.0"):
+def set_axis(obj: T, index: Any, implementation: PANDAS_IMPLEMENTATIONS) -> T:
+    backend = get_backend(implementation)
+    backend_verison = parse_version(backend.__version__)
```
Comment (MarcoGorelli) [inline narwhals/_pandas_like/utils.py:358]: we don't need to parse the version for non-pandas implementations here?

File: narwhals/dependencies.py [hunk 9]
```diff
@@ -15,6 +19,15 @@
     import pandas
 
 
+class Implementation(Enum):
+    POLARS = auto()
+    PANDAS = auto()
+    MODIN = auto()
+    CUDF = auto()
+    PYARROW = auto()
+    NUMPY = auto()
```
Comment (MarcoGorelli) [inline narwhals/dependencies.py:28]: what's this?

File: narwhals/typing.py [hunk 10]
```diff
@@ -32,4 +33,9 @@ def join(self, *args: Any, **kwargs: Any) -> Any: ...
 # Anything which can be converted to a Narwhals DataFrame.
 IntoDataFrame: TypeAlias = Union["NativeDataFrame", "DataFrame"]
 
-__all__ = ["IntoExpr", "IntoDataFrame"]
+
+def assert_never(_: NoReturn) -> NoReturn:
+    raise AssertionError("Expected code to be unreachable")
+
+
+__all__ = ["IntoExpr", "IntoDataFrame", "assert_never"]
```
Comment (MarcoGorelli) [inline narwhals/typing.py:41]: not sure `assert_never` should be a public type, it's only used internally here

Comment (ELC) [reply narwhals/typing.py:41]: If we put a leading underscore, it will make I private *to the typing module*, it is internal, but there are no naming conventions for internal members. That is, it is used in other modules of the package however not intended to be used outside the package

File: narwhals/dependencies.py (hunk 9 above)
Comment (ELC) [reply narwhals/dependencies.py:28]: This is the enum where we register the different implementations, whenever we add a new one, we need to add it here and MyPy will flag all the necessary changes

File: narwhals/_pandas_like/utils.py (hunk 8 above)
Comment (ELC) [reply narwhals/_pandas_like/utils.py:358]: It was written this way to avoid using `get_pandas`, the idea with the enum is that now we only expose and use `get_backend`, making he function agnostic on how that backend is loaded

File: narwhals/_pandas_like/implementations.py (hunk 7 above)
Comment (ELC) [reply narwhals/_pandas_like/implementations.py:14]: Me neither, feel free to suggest any name

File: narwhals/_pandas_like/dataframe.py (hunk 6 above)
Comment (ELC) [reply narwhals/_pandas_like/dataframe.py:290]: Unfortunately MyPy only supports type narrowing in Enums with the `is` operator. Runtime behaviour is identical but MyPy will not narrow the type unless done this way

I believe this is because `in` uses `==` and not `is` internally but I am not totally sure

File: .pre-commit-config.yaml (hunk 5 above)
Comment (ELC) [reply .pre-commit-config.yaml:18]: It is but, since we are explicitly using it in some imports, I believe it is better to have pinned it.

Just because *explicit is better than implicit*

**Comment by ELC** [comment]
I will resolve the conflicts later today. They all are about the same theme, the files need to use the `get_backend` facade instead of the concrete `get_*`

File: narwhals/dependencies.py (hunk 9 above)
Comment (MarcoGorelli) [reply narwhals/dependencies.py:28]: Sorry I mean, why numpy?

File: narwhals/_pandas_like/utils.py (hunk 8 above)
Comment (MarcoGorelli) [reply narwhals/_pandas_like/utils.py:358]: sure but you don't need to call `parse_version` for non-pandas implementations here

File: narwhals/dependencies.py (hunk 9 above)
Comment (ELC) [reply narwhals/dependencies.py:29]: Because there are a couple of places where we call  `get_backend` with `Implementation.Numpy`. The idea behind the enums is to always access the compute backend through `get_backend`.

This is not fully done yet, but after this PR is merge, I can work on replacing all the intances of `get_*` with the `get_backend`. At the moment there is only two places, which are the entrypoints.

The rationale behind this is to make the code fully compute backend agnostic

File: narwhals/_pandas_like/utils.py (hunk 8 above)
Comment (ELC) [reply narwhals/_pandas_like/utils.py:363]: It was just to make it easier on the eyes, we can move the `parse_version` into the condition expression

**Comment by ELC** [comment]
Finished with all modifications, tests are passing with 100% coverage and I simplify some of the functions as well to leverage the enums.

Let me know your thoughts

@MarcoGorelli / @EdAbati

File: narwhals/dependencies.py (hunk 9 above)
Comment (MarcoGorelli) [reply narwhals/dependencies.py:33]: sure, but we don't have a numpy backend?

I mean, pandas uses it under-the-hood, but as far as narwhals is concerned, the dataframe backend is pandas, not numpy

**Review by MarcoGorelli — COMMENTED** [review]
thanks for your PR

I don't think we can get rid of the `get_*` functions, they're part of the public API, and are already used

https://github.com/FBruzzesi/timebasedcv/blob/ce0205173c883574372168dfd4b63e46ccfb621a/timebasedcv/splitstate.py#L17

internal cleanups are fine, but the public api should remain stable (we can make exceptions in some cases, but not if some part of the API is already being used)

**Comment by ELC** [comment]
This then becomes a design question, I can revert back to continue exposing the `get_*` functions but internally we should only use the `get_backend`

The value of narwhals is to provide an abstraction over the dataframe engine, if one can access individual engines, it is leaking the abstraction. 

For the internal package use case, adding a new engine should not require changing if/elif/else in many places, there should be abstractions in place so that only one place (like `dependencies.py`) needs to be modified, in addition to the concrete folder of that implementation. 

If a consumer code needs a particular engine, they should import it directly, not through narwhals, specially because narwhals cannot guarantee the engine will be available.

I don't know exactly what is the vision but I assumed that someone using narwhals will like to remove most of the engine specifics and just use the engine for I/O and narwhals for expressions, hence using something like `get_pandas` from consumer code seemed unexpected to me

File: narwhals/dependencies.py (hunk 9 above)
Comment (ELC) [reply narwhals/dependencies.py:33]: That is true, I just wanted to abstract the way we interact with dependencies from within the package to avoid calling `get_numpy` directly and use the `get_backend` function. This may be a little misleading as Numpy is not a backend pre se. It was just for convenience.

However to further limit the scope of what is and what is not a dataframe engine, I created two types below `DATAFRAME_IMPLEMENTATIONS` and `SERIES_IMPLEMENTATIONS` which do not include Numpy. They are both thought to be subset of this `Implementation` enum. That means though that maybe `Implementation` is not the best name for this.

I wanted the enum to capture everything that was external, be it an auxiliary library like numpy or pyarrow_compute or a dataframe engine like pandas

**Comment by ELC** [comment]
@MarcoGorelli is this ready to merge or are there other changes you would like to include?

File: narwhals/dependencies.py (hunk 9 above)
Comment (MarcoGorelli) [reply narwhals/dependencies.py:33]: I don't think numpy and pyarrow.compute really belong here

I'd suggest just having `Implementation` here, and then `PandasImplementation`

Comment (ELC) [reply narwhals/dependencies.py:33]: And to make sure that both `pyarrow.compute` and `numpy` are loadable by the `get_backend` function, how should we name that Enum? It should be different than `Implementation`

Comment (MarcoGorelli) [reply narwhals/dependencies.py:33]: we can just use `get_numpy` / `get_pyarrow_compute`

File: noxfile.py [hunk 11]
```diff
@@ -33,7 +33,7 @@ def pytest_coverage(session: Session) -> None:
 @nox.session(python=PYTHON_VERSIONS[0])  # type: ignore[misc]
 def minimum_versions(session: Session) -> None:
     session.install(
-        "pandas==0.25.3",
+        "pandas==1.1.5",
```
Comment (ELC) [inline noxfile.py:36]: @MarcoGorelli I made this change because tests are not passing. Pyarrow does not support `pandas< 1.0.0`.

Tests were broken by merging #404

File: narwhals/dependencies.py (hunk 9 above)
Comment (ELC) [reply narwhals/dependencies.py]: Done

File: noxfile.py (hunk 11 above)
Comment (MarcoGorelli) [reply noxfile.py:36]: could you clarify please? looks like that PR (and the associated merge to main) pass CI https://github.com/narwhals-dev/narwhals/commits/main/ ?

Comment (ELC) [reply noxfile.py:36]: These are some of the errors I see when running test locally on latest version of main:

```text
UNEXPECTED EXCEPTION: AttributeError("'DataFrame' object has no attribute 'convert_dtypes'")
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest narwhals.utils.maybe_convert_dtypes[6]>", line 1, in <module>
  File "/workspaces/narwhals/narwhals/utils.py", line 261, in maybe_convert_dtypes
    df_any._dataframe._dataframe.convert_dtypes(*args, **kwargs)
  File "/workspaces/narwhals/.nox/minimum_versions/lib/python3.8/site-packages/pandas/core/generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'convert_dtypes'
/workspaces/narwhals/narwhals/utils.py:249: UnexpectedException
```


```text
UNEXPECTED EXCEPTION: ImportError('pyarrow requires pandas 1.0.0 or above, pandas 0.25.3 is installed')
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest narwhals.series.Series.to_pandas[8]>", line 1, in <module>
  File "/workspaces/narwhals/narwhals/translate.py", line 400, in wrapper
    result = func(*args, **kwargs)
  File "<doctest narwhals.series.Series.to_pandas[6]>", line 3, in func
  File "/workspaces/narwhals/narwhals/series.py", line 1209, in to_pandas
    return self._series.to_pandas()
  File "/workspaces/narwhals/.nox/minimum_versions/lib/python3.8/site-packages/polars/series/series.py", line 4434, in to_pandas
    else self.to_arrow().to_pandas(**kwargs)
  File "pyarrow/array.pxi", line 830, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/array.pxi", line 1426, in pyarrow.lib.Array._to_pandas
  File "pyarrow/array.pxi", line 1649, in pyarrow.lib._array_like_to_pandas
  File "pyarrow/pandas-shim.pxi", line 103, in pyarrow.lib._PandasAPIShim.series
  File "pyarrow/pandas-shim.pxi", line 96, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 65, in pyarrow.lib._PandasAPIShim._import_pandas
ImportError: pyarrow requires pandas 1.0.0 or above, pandas 0.25.3 is installed
/workspaces/narwhals/narwhals/series.py:1203: UnexpectedException
```

```text
______________________________________________ [doctest] narwhals.expression.ExprDateTimeNamespace.total_seconds ______________________________________________
2635 
2636             We define a dataframe-agnostic function:
2637 
2638             >>> @nw.narwhalify
2639             ... def func(df):
2640             ...     return df.with_columns(a_total_seconds=nw.col("a").dt.total_seconds())
2641 
2642             We can then pass either pandas or Polars to `func`:
2643 
2644             >>> func(df_pd)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -                       a  a_total_seconds
    -0        0 days 00:00:10               10
    -1 0 days 00:00:20.040000               20
    +                a  a_total_seconds
    +0        00:00:10               10
    +1 00:00:20.040000               20

/workspaces/narwhals/narwhals/expression.py:2644: DocTestFailure
```

They all appear when running doctest with minimum versions. However, CICD passes just fine, so I am concerned there is a misconfiguration somewhere, probably missing a couple of `skipif`s. The error clearly states that `Pyarrow` requires `pandas >=1.0.0`

Comment (ELC) [reply noxfile.py]: @MarcoGorelli I believe I found the causes:

1. The `minimum_versions` is running `pandas==0.25.3` but wihtout the `--doctest-modules` - [Source](https://github.com/narwhals-dev/narwhals/blob/cc2c1f11983f48122d102d22382468192c13737e/.github/workflows/extremes.yml#L9-L34)
2. The `pretty_old_versions` is running `--doctest-modules` but without `pandas==0.25.3`, it is using `pandas==1.1.5` - [Source](https://github.com/narwhals-dev/narwhals/blob/cc2c1f11983f48122d102d22382468192c13737e/.github/workflows/extremes.yml#L36-L63)

Was this made purposely? If so, the noxfile and the tests do not accurately reflect what the CICD does

Comment (MarcoGorelli) [reply noxfile.py]: ah thanks - I don't use nox myself, another dev added it, it should probably be updated

**Comment by MarcoGorelli** [comment]
thanks for your pr 🙏  there's some changes I agree with, others not so much - I'll add a commit later before merging

**Comment by ELC** [comment]
Great this got merged!

I don't see the `get_backend` functionality in the final set of changes, are you suggesting I made a separete PR for those or was that accidentally lost in the last force push?
